services: docker
git:
  depth: false
install: make docker-login build-docker
stages:
- name: test
- name: publish-docker
jobs:
  include:
  - stage: test
    name: Publish docker image
    script:
    - make run-docker
  - stage: publish
    name: Publish docker image
    script:
    - make docker-login publish-docker
env:
  global:
  - secure: EYW9k/0RWTqb4IGl02GLKjDpDVWK55jHkfFHlfnJJnEUcbh3P5CtNnejZHk7DUydoqMgj4arxKWyexj/K9NxOpnMO8i30XICCB9XZVpaaLPQlfxh/k0zqmfY5U5Xjuol3MAjLcd/uotx/HEIyb9ghtxvUkZhi08cDkJwvqPgcpv8aHNB+01/GbXLzXuysegMznZEgo5LBS/dRWw8eSBAWPLUG0zhd1dfV/JPbK0ABsV2YysePmW1+MyHo8A/AW315/aToz3SM48Rhir2vB8W7PuJb6NaJd8D+lVs40GT/P4hPzZWkqb29wz1YdOfjr1XnH0NQrW/T8wVE1VaCwwBEQsBf6cQB/jrMhLUUyLxvP+AtV07HzDZvgqS05Jg89L77h+QFozDai78qb9QpoCloYDuke5e6Y9fQfmdTnGSBDJQxAFD+RPiTkBeukSzjtYpBuErsrbA5VbHgSXn+jTycbgWGvyBxD3aAYkCNBPe4jbEwQgzoB168d+4UhHXsMCFsF+uBgsB8+AhJVZwfLmIWaPFPZmY21HYglJucPA81tJP+kLiTTsYuw6MwYbm97jbCZpbJOjQlnPNsMID9dIfHYGUmcaRN84+U22NvxTsELplAoxEss71rmI/JtmOvwxh7KMwE58Z2+/ADcIAHmHPmC1AxrXn63pSFnazmymONVM=
  - secure: Vka6iia7oAOjRbrWDRy9MlSHkCBKb3TlJ/hbwsRUT6jkRQZmvZHwh8xLQ0zVFiA5DjNdMlj/RX9X3Aj1fjUXi2yld9/aZzgBBTXDWp6h+9a3zeH6pHA9u8k+wnKPmyPrjAAtlqdYKA6XgIzOOfYZLRhSVOS8h7M0ny+bJlulRTwGQf8b5FzFpfNEeTXnplWYKedLuSQs7uK2HLoEZgDrRm4bsCBiJnOAYZm/5J4WpEfFcCoM73CpPf1Vrs/5AFU2HXHuEGGEs2SY8i1ruGjuzEP0M9uxCGpNqu57/DrEmsAWlVUihykT7m51TP+vXYLo02jdGetVI5To6JoI4vsFSnbSnhk7Zr3FJDm2W4fY6a7HkXdzKmrSDBomtv86gkDHqC0q/7zl8RPDcOq7T0JYZeS2meMFSmnqzSJQHJP25++d9XmtfYuBwgGcwsL4H7CVKjkZIvo6XwrS7eQXYm96Lo4G5SY525wwKlzd18ookaM7tjyur6AJ9fgrIwzDeCOKBsQ1XDlmOOWRyT06DVyR1vkSPtuWEb0UXKohoztN/yR7aG6nydSClstxHnyQNPZaj8kbFp661k1qDonR+JbBO9xnStblcBR/qsjMRe6uRteeyKIca5GOkRhfwCIzschR6x7D9TeBsGPBMhlGA7chiJsmhGQqBgC+1FbyzQ6QDR0=
